#! /bin/sh

case "$-" in
*i*) ;;
*)  if [ "$1" != "-f" ]; then # allow use from scripts, as ". setenv -f"
        echo "Error: not a login shell -- run this script as 'source setenv' or '. setenv'"
        exit 1
    fi
esac

export SS5G_ROOT=`pwd`
echo "$SS5G_ROOT added to PATH"
export PATH=$SS5G_ROOT/bin:$PATH
